### ISSUE TITLE
file mode of templates and files are wrong

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-elasticsearch#20]
> Mode the file or directory should be. For those used to /usr/bin/chmod remember that modes are actually octal numbers (like 0644). Leaving off the leading zero will likely have unexpected results. As of version 1.8, the mode may be specified as a symbolic mode (for example, u+rwx or u=rw,g=r,o=r).

https://github.com/reallyenglish/ansible-role-elasticsearch/blob/master/tasks/configure-jvm-FreeBSD.yml#L6

```yaml
- name: Create /etc/rc.conf.d if it does not exist
  file:
    path: /etc/rc.conf.d
    mode: 755
    state: directory
```
